<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.22.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq Content Editors for Orchard Core</Title>
    <CopyrightYear>2021</CopyrightYear>
    <DescriptionBody>Module for managing advanced content editing processes based on editor groups and asynchronous operations.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Editor;ContentEditor;AsyncEditor</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Content-Editors</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentFields" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Media" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\Lombiq.VueJs\Lombiq.VueJs.Resources\Lombiq.VueJs.Resources.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.VueJs.Resources" Version="9.0.2-alpha.4.osoe-925" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.22.osoe-925" />
</Project>
